# Generated by Django 6.0.6 on 2026-07-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alimento_galpon_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
